### ISSUE TITLE
Running server.go: Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by devrsw** [supergiant/supergiant#146]
Getting an issue when running server.go:

````
panic: Cannot add a NOT NULL column with default value NULL

goroutine 1 [running]:
panic(0x47ce520, 0xc420183e60)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/supergiant/supergiant/pkg/core.(*Core).Initialize(0xc42037a1c0)
	/Users/[]/golang/src/github.com/supergiant/supergiant/pkg/core/core.go:92 +0x78
main.main.func1(0xc420310280)
	/Users/[]/golang/src/github.com/supergiant/supergiant/cmd/server/server.go:25 +0x3e
github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli.(*App).Run(0xc42007b080, 0xc42007c090, 0x3, 0x3, 0x0, 0x0)
	/Users/[]/golang/src/github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli/app.go:201 +0xba7
main.main()
	/Users/[]/golang/src/github.com/supergiant/supergiant/cmd/server/server.go:132 +0xb50
exit status 2
````

**Comment by FestivalBobcats** [comment]
This is due to a stale database schema. You will need to delete the SQLite file you have specified in your config.json.

In the future (especially >= 1.0), there will be upgrade/migration instructions when the database schema changes. For now, migrations are left to the user.

**Comment by devrsw** [comment]
Ok, going to close this issue then and open up a better-named issue about migrations.
