### ISSUE TITLE
Invalid character 'ï' looking for beginning of value

### ISSUE THREAD

**Issue by gpls** [supergiant/supergiant#208]
I'm attempting to [Run a Supergiant Server on DigitalOcean](https://supergiant.io/blog/how-to-run-supergiant-server-digitalocean), but whenever I try Step 4: Create an Admin User, using:

`sudo supergiant --config-file /etc/supergiant/config.json`

I get:

`panic: invalid character 'ï' looking for beginning of value`

I also just started using Bitvise xterm on Windows10 Pro and edited config.json to suggested values via Bitvise with Sublime, not sure if that helps.

Any suggestions?

**Comment by gopherstein** [comment]
Can you post your config?

**Comment by gpls** [comment]
```
{
  "sqlite_file": "/var/lib/supergiant/development.db",
  "ui_enabled": true,
  "capacity_service_enabled": true,
  "publish_host": "localhost",
  "http_port": "8080",
  "log_file": "/var/log/supergiant/development.log",
  "log_level": "debug",
  "node_sizes": {
    "aws": [
      {"name": "t2.nano", "ram_gib": 0.5, "cpu_cores": 1},
      {"name": "t2.micro", "ram_gib": 1, "cpu_cores": 1},
      {"name": "t1.micro", "ram_gib": 0.613, "cpu_cores": 1},
      {"name": "t2.small", "ram_gib": 2, "cpu_cores": 1},
      {"name": "m1.small", "ram_gib": 1.7, "cpu_cores": 1},
      {"name": "t2.medium", "ram_gib": 4, "cpu_cores": 2},
      {"name": "m3.medium", "ram_gib": 3.75, "cpu_cores": 1},
      {"name": "m1.medium", "ram_gib": 3.75, "cpu_cores": 1},
      {"name": "t2.large", "ram_gib": 8, "cpu_cores": 2},
      {"name": "c3.large", "ram_gib": 3.75, "cpu_cores": 2},
      {"name": "c4.large", "ram_gib": 3.75, "cpu_cores": 2},
      {"name": "m4.large", "ram_gib": 8, "cpu_cores": 2},
      {"name": "c1.medium", "ram_gib": 1.7, "cpu_cores": 2},
      {"name": "m3.large", "ram_gib": 7.5, "cpu_cores": 2},
      {"name": "r3.large", "ram_gib": 15.25, "cpu_cores": 2},
      {"name": "m1.large", "ram_gib": 7.5, "cpu_cores": 2},
      {"name": "c4.xlarge", "ram_gib": 7.5, "cpu_cores": 4},
      {"name": "c3.xlarge", "ram_gib": 7.5, "cpu_cores": 4},
      {"name": "m4.xlarge", "ram_gib": 16, "cpu_cores": 4},
      {"name": "m2.xlarge", "ram_gib": 17.1, "cpu_cores": 2},
      {"name": "m3.xlarge", "ram_gib": 15, "cpu_cores": 4},
      {"name": "r3.xlarge", "ram_gib": 30.5, "cpu_cores": 4},
      {"name": "m1.xlarge", "ram_gib": 15, "cpu_cores": 4},
      {"name": "c4.2xlarge", "ram_gib": 15, "cpu_cores": 8},
      {"name": "c3.2xlarge", "ram_gib": 15, "cpu_cores": 8},
      {"name": "m4.2xlarge", "ram_gib": 32, "cpu_cores": 8},
      {"name": "m2.2xlarge", "ram_gib": 34.2, "cpu_cores": 4},
      {"name": "c1.xlarge", "ram_gib": 7, "cpu_cores": 8},
      {"name": "m3.2xlarge", "ram_gib": 30, "cpu_cores": 8},
      {"name": "g2.2xlarge", "ram_gib": 15, "cpu_cores": 8},
      {"name": "r3.2xlarge", "ram_gib": 61, "cpu_cores": 8},
      {"name": "d2.xlarge", "ram_gib": 30.5, "cpu_cores": 4},
      {"name": "c4.4xlarge", "ram_gib": 30, "cpu_cores": 16},
      {"name": "c3.4xlarge", "ram_gib": 30, "cpu_cores": 16},
      {"name": "i2.xlarge", "ram_gib": 30.5, "cpu_cores": 4},
      {"name": "m4.4xlarge", "ram_gib": 64, "cpu_cores": 16},
      {"name": "m2.4xlarge", "ram_gib": 68.4, "cpu_cores": 8},
      {"name": "r3.4xlarge", "ram_gib": 122, "cpu_cores": 16},
      {"name": "d2.2xlarge", "ram_gib": 61, "cpu_cores": 8},
      {"name": "c4.8xlarge", "ram_gib": 60, "cpu_cores": 36},
      {"name": "c3.8xlarge", "ram_gib": 60, "cpu_cores": 32},
      {"name": "i2.2xlarge", "ram_gib": 61, "cpu_cores": 8},
      {"name": "cc2.8xlarge", "ram_gib": 60.5, "cpu_cores": 32},
      {"name": "cg1.4xlarge", "ram_gib": 22.5, "cpu_cores": 16},
      {"name": "m4.10xlarge", "ram_gib": 160, "cpu_cores": 40},
      {"name": "g2.8xlarge", "ram_gib": 60, "cpu_cores": 32},
      {"name": "r3.8xlarge", "ram_gib": 244, "cpu_cores": 32},
      {"name": "d2.4xlarge", "ram_gib": 122, "cpu_cores": 16},
      {"name": "hi1.4xlarge", "ram_gib": 60.5, "cpu_cores": 16},
      {"name": "i2.4xlarge", "ram_gib": 122, "cpu_cores": 16},
      {"name": "cr1.8xlarge", "ram_gib": 244, "cpu_cores": 32},
      {"name": "hs1.8xlarge", "ram_gib": 117, "cpu_cores": 16},
      {"name": "d2.8xlarge", "ram_gib": 244, "cpu_cores": 36},
      {"name": "i2.8xlarge", "ram_gib": 244, "cpu_cores": 32}
    ],
    "digitalocean": [
      {"name": "512mb", "ram_gib": 0.5, "cpu_cores": 1},
      {"name": "1gb", "ram_gib": 1, "cpu_cores": 1},
      {"name": "2gb", "ram_gib": 2, "cpu_cores": 2},
      {"name": "4gb", "ram_gib": 4, "cpu_cores": 2},
      {"name": "8gb", "ram_gib": 8, "cpu_cores": 4},
      {"name": "16gb", "ram_gib": 16, "cpu_cores": 8},
      {"name": "32gb", "ram_gib": 32, "cpu_cores": 12},
      {"name": "48gb", "ram_gib": 48, "cpu_cores": 16},
      {"name": "64gb", "ram_gib": 64, "cpu_cores": 20}
    ],
    "gce": [
      {"name": "n1-standard-1", "ram_gib": 3.75, "cpu_cores": 1},
      {"name": "n1-standard-2", "ram_gib": 7.5, "cpu_cores": 2},
      {"name": "n1-standard-4", "ram_gib": 15, "cpu_cores": 4},
      {"name": "n1-standard-8", "ram_gib": 30, "cpu_cores": 8}
    ]
  }
}
```

**Comment by gopherstein** [comment]
I am recreating.... just a few mins...

**Comment by gpls** [comment]
thank you

**Comment by gpls** [comment]
I found [this](http://stackoverflow.com/questions/31398044/got-error-invalid-character-%C3%AF-looking-for-beginning-of-value-from-json-unmar) on stackoverflow, but don't know how or if it might help

**Comment by gopherstein** [comment]
Which version are you running? I am able to get it running per the doc with this version:
curl https://github.com/supergiant/supergiant/releases/download/v0.14.3/supergiant-server-linux-

**Comment by gpls** [comment]
this is the release i used:
https://github.com/supergiant/supergiant/releases/download/v0.14.3/supergiant-server-linux-amd64

**Comment by gopherstein** [comment]
Here is my full command list:
```
curl https://github.com/supergiant/supergiant/releases/download/v0.14.3/supergiant-server-linux-amd64 -L -o /usr/bin/supergiant
chmod +x /usr/bin/supergiant
```
I copied the example config: https://github.com/supergiant/supergiant/blob/master/config/config.json.example
into `/etc/supergiant/config.json` then edited these lines.
```
{
 ...
 "sqlite_file": "/var/lib/supergiant/development.db",
 ...
 "log_file": "/var/log/supergiant/development.log",
 ...
}
```
then running `sudo supergiant --config-file /etc/supergiant/config.json` I got my admin creds and the server started.

If these don't work, can you confirm the OS you are using?

**Comment by gpls** [comment]
Yes, those are the same commands I used. The server is running Ubuntu 16.04.2

**Comment by gpls** [comment]
here's the stack trace


```
panic: invalid character 'ï' looking for beginning of value

goroutine 1 [running]:
panic(0xd4b400, 0xc4203600a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/supergiant/supergiant/pkg/core.(*Core).Initialize(0xc4202a43c0)
        /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/core.go:102 +0x10a
main.main.func1(0xc4201f5040)
        /ext-go/1/src/github.com/supergiant/supergiant/cmd/server/server.go:32 +0x49
github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli.(*App).Run(0xc420075e40, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
        /ext-go/1/src/github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli/app.go:201 +0xba7
main.main()
        /ext-go/1/src/github.com/supergiant/supergiant/cmd/server/server.go:162 +0xbed
```

**Comment by gopherstein** [comment]
If you cat that config file, you don't see an out of place 'i' in the json?

**Comment by gopherstein** [comment]
Like is you pasted it via vim, you would use 'i' to insert the text?

**Comment by gpls** [comment]
When I cat the config file, I don't see an out-of-place 'i'. I think the error i received referred to a small 'i' with an umlaut, 'ï'. [This link](http://stackoverflow.com/questions/31398044/got-error-invalid-character-%C3%AF-looking-for-beginning-of-value-from-json-unmar) indicates that possibly a byte-order-mark may be an issue, but I don't know if it is or how to apply a fix.

**Comment by gpls** [comment]
i performed the following actions:

1. Create droplet - Ubuntu 16.04.2 - 512mb

2. Get Supergiant

	a. Download

		curl https://github.com/supergiant/supergiant/releases/download/v0.14.3/supergiant-server-linux-amd64 -L -o /usr/bin/supergiant

	b. Adjust Permissions

		chmod +x /usr/bin/supergiant

3. Configure Supergiant

	a. Download example config.json

		curl https://github.com/supergiant/supergiant/blob/master/config/config.json.example --create-dirs -o /etc/supergiant/config.json
  
  b. Reconfigure

		{
		 ...
		 "sqlite_file": "/var/lib/supergiant/development.db",
		 ...
		 "log_file": "/var/log/supergiant/development.log",
		 ...
		}

  c. Create directories

    mkdir /var/lib/supergiant && sudo mkdir /var/log/supergiant

  d. Create file: /etc/systemd/system/supergiant.service

		[Unit]
		Description=Supergiant Server
		After=syslog.target
		After=network.target
		[Service]
		ExecStart=/usr/bin/supergiant --config-file /etc/supergiant/config.json
		Restart=on-abort
		[Install]
		WantedBy=multi-user.target    

4. Create an Admin User

  supergiant --config-file /etc/supergiant/config.json

this is when i get the error:

`panic: invalid character 'ï' looking for beginning of value`

**Comment by gopherstein** [comment]
huh.... weird. I am wondering if it is a byte issue like you posted related to the terminal you are using.

Lets try this... go ahead and start the service: `sudo systemctl start supergiant.service`

then check the logs to see if you get your password.

```
root@ubuntu-512mb-nyc3-01:~# journalctl | grep supergiant
Apr 10 20:44:19 ubuntu-512mb-nyc3-01 sudo[1760]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/mkdir /var/lib/supergiant
Apr 10 20:44:19 ubuntu-512mb-nyc3-01 sudo[1762]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/mkdir /var/log/supergiant
Apr 10 20:47:11 ubuntu-512mb-nyc3-01 sudo[1816]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl start supergiant.service
Apr 10 20:47:11 ubuntu-512mb-nyc3-01 supergiant[1819]: time="2017-04-10T20:47:11Z" level=info msg="No Admin detected, creating new and printing credentials:"
Apr 10 20:47:12 ubuntu-512mb-nyc3-01 supergiant[1819]:   ( ͡° ͜ʖ ͡°)  USERNAME: admin  PASSWORD: XXXXXXXXXX
Apr 10 20:47:12 ubuntu-512mb-nyc3-01 supergiant[1819]: time="2017-04-10T20:47:12Z" level=info msg="Registering stable HelmRepo"
Apr 10 20:47:12 ubuntu-512mb-nyc3-01 supergiant[1819]: Writing log to /var/log/supergiant/development.log
root@ubuntu-512mb-nyc3-01:~#
```

**Comment by gpls** [comment]
```
root@sg:~# sudo systemctl start supergiant.service
root@sg:~# journalctl | grep supergiant
Apr 10 18:12:58 sg sudo[19380]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/curl https://github.com/supergiant/supergiant/blob/master/config/config.json.example --create-dirs -o /etc/supergiant/config.json
Apr 10 18:30:30 sg sudo[19404]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/mkdir /var/log/supergiant
Apr 10 19:08:51 sg sudo[19449]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/supergiant --config-file /etc/supergiant/config.json
Apr 10 19:15:55 sg sudo[19453]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/supergiant --config-file /etc/supergiant/config.json
Apr 10 19:20:36 sg sudo[19463]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/supergiant --config-file /etc/supergiant/config.json
Apr 10 19:23:06 sg sudo[19468]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/supergiant --config-file /etc/supergiant/config.json
Apr 10 19:23:18 sg sudo[19472]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/supergiant --config-file /etc/supergiant/config.json
Apr 10 20:51:13 sg sudo[19508]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/systemctl start supergiant.service
Apr 10 20:51:13 sg supergiant[19511]: panic: invalid character 'ï' looking for beginning of value
Apr 10 20:51:13 sg supergiant[19511]: goroutine 1 [running]:
Apr 10 20:51:13 sg supergiant[19511]: panic(0xd4b400, 0xc42035e080)
Apr 10 20:51:13 sg supergiant[19511]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 10 20:51:13 sg supergiant[19511]: github.com/supergiant/supergiant/pkg/core.(*Core).Initialize(0xc4202a23c0)
Apr 10 20:51:13 sg supergiant[19511]:         /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/core.go:102 +0x10a
Apr 10 20:51:13 sg supergiant[19511]: main.main.func1(0xc4201f1040)
Apr 10 20:51:13 sg supergiant[19511]:         /ext-go/1/src/github.com/supergiant/supergiant/cmd/server/server.go:32 +0x49
Apr 10 20:51:13 sg supergiant[19511]: github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli.(*App).Run(0xc420071e40, 0xc42000c0f0, 0x3, 0x3, 0x0, 0x0)
Apr 10 20:51:13 sg supergiant[19511]:         /ext-go/1/src/github.com/supergiant/supergiant/vendor/github.com/codegangsta/cli/app.go:201 +0xba7
Apr 10 20:51:13 sg supergiant[19511]: main.main()
Apr 10 20:51:13 sg supergiant[19511]:         /ext-go/1/src/github.com/supergiant/supergiant/cmd/server/server.go:162 +0xbed
Apr 10 20:51:13 sg systemd[1]: supergiant.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 10 20:51:13 sg systemd[1]: supergiant.service: Unit entered failed state.
Apr 10 20:51:13 sg systemd[1]: supergiant.service: Failed with result 'exit-code'.
```

**Comment by gopherstein** [comment]
Damn.... Is there anything nonstandard with your droplet? like any network settings etc?

Also @FestivalBobcats @ben any other ideas?

**Comment by gpls** [comment]
i did select private networking, ipv6 address, and its on sfo2, plus auto backups

**Comment by gopherstein** [comment]
ok, trying again with edited networking.

**Comment by FestivalBobcats** [comment]
The failing line deals with parsing the JSON config file, so I'm assuming it has to be that. I clicked that StackOverflow link -- this **definitely** seems like some obscure Microsoft encoding thing. The SO thread mentioned we could try TrimPrefix in the config parsing code, like this:

```go
bytes.TrimPrefix(body, []byte("\xef\xbb\xbf"))
```

https://github.com/supergiant/supergiant/blob/master/pkg/core/core.go#L119-L125

^^ that block of code would need to be replaced so that the file was first read in as bytes (as opposed to being fed directly to the JSON Decoder), and TrimPrefix used before unmarshaling the JSON bytes directly.

**Comment by FestivalBobcats** [comment]
But, the thing is: if you edited this JSON with a Windows-based editor... maybe just try editing the JSON inside Linux?

That would prevent having to go through the whole build cycle / testing to get you up and running.

**Comment by gpls** [comment]
i see. ok, it may be a little while before i get to try this. but I will try it and let you know what happens. Thank you so far for your help. I really appreciate it!

**Comment by gopherstein** [comment]
Welp... tried a bunch of different network configs like you have setup, and cannot re-create the issue.

**Comment by gopherstein** [comment]
It has been a while since I used a Windows based terminal... But I used to have character issues back when I used to use Putty.  I would agree with @FestivalBobcats. I think the next step would be to try and re-create the config file using a different terminal app, or from a linux based terminal and see if that makes a difference.

**Comment by gpls** [comment]
will do. thanks again, and i'll be sure to test and let you know

**Comment by gpls** [comment]
Making config.json changes from the server got it working.

Thanks for helping, everyone!
