### ISSUE TITLE
SuperGiant crashes on new pod resource

### ISSUE THREAD

**Issue by digitalsparky** [supergiant/supergiant#211]
Trying to add the following pod to test via the Pods -> New:

```
{
  "kube_name": "senseict",
  "namespace": "default",
  "kind": "Pod",
  "name": "helloworld",
  "resource": {
    "metadata": {
      "labels": {
        "service": "helloworld"
      }
    },
    "spec": {
      "containers": [
        {
          "name": "app",
          "image": "tutum/hello-world"
        }
      ]
    }
  }
}
```

Results in SuperGiant crashing with the following message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a3242]

goroutine 6520 [running]:
panic(0xd6b440, 0xc420018030)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/supergiant/supergiant/pkg/core.(*DefaultProvisioner).Provision(0xc420023718, 0xc420764d00, 0x7, 0x0)
        /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/provisioner_default.go:17 +0x62
github.com/supergiant/supergiant/pkg/core.(*KubeResources).Start.func1(0xc420601380, 0x0, 0xc420e87980)
        /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/kube_resources.go:152 +0xc6
github.com/supergiant/supergiant/pkg/core.(*Action).Async.func1(0xc420601380)
        /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/action.go:72 +0x4a
created by github.com/supergiant/supergiant/pkg/core.(*Action).Async
        /ext-go/1/src/github.com/supergiant/supergiant/pkg/core/action.go:93 +0x22d

```

The same issue occurs when attempting to add a new Service in as well.

This is all via the web interface.

**Comment by digitalsparky** [comment]
Env note:

This is the 64bit daemon, tried with both SSL enabled and disabled, using DigitalOcean as the provider

**Comment by gopherstein** [comment]
I will try to re-create this as soon as I can.

**Comment by gopherstein** [comment]
The error the panic refers to is a translation error with the JSON.

**Comment by gopherstein** [comment]
@digitalsparky nice find. Looks like this was global.

**Comment by digitalsparky** [comment]
Wowzers, good to have it fixed then! :)
