### ISSUE TITLE
We need to avoid ever using panics if possible and return errors.New("") msgs. Specifically with resources that don't exist.

### ISSUE THREAD

**Issue by spankenstein** [supergiant/supergiant#36]
```
spankenstein@Workhole supergiant-cli (master) $ go install; supergiant-cli component create test --app test2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x95ab5]

goroutine 1 [running]:
panic(0x4b97a0, 0xc8200140c0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/supergiant/supergiant-cli/apictl.CreateComponent(0x7fff5fbff8b0, 0x4, 0xc8200155da, 0x5, 0x0, 0x0)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/supergiant/supergiant-cli/apictl/component.go:26 +0x435
main.componentCommands.func1(0xc82008cc80)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/supergiant/supergiant-cli/component_commands.go:23 +0x197
github.com/codegangsta/cli.Command.Run(0x559f08, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x600e80, 0x34, 0x0, ...)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc82008ca00, 0xc82008c8c0, 0x0, 0x0)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/codegangsta/cli/app.go:298 +0x11c9
github.com/codegangsta/cli.Command.startApp(0x567160, 0x9, 0x0, 0x0, 0xc820015350, 0x1, 0x1, 0x5d7780, 0x22, 0x0, ...)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/codegangsta/cli/command.go:249 +0x74f
github.com/codegangsta/cli.Command.Run(0x567160, 0x9, 0x0, 0x0, 0xc820015350, 0x1, 0x1, 0x5d7780, 0x22, 0x0, ...)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/codegangsta/cli/command.go:65 +0x79
github.com/codegangsta/cli.(*App).Run(0xc82008c780, 0xc82000a120, 0x6, 0x6, 0x0, 0x0)
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
	/Users/spankenstein/src/qbox/golang_projects/src/github.com/supergiant/supergiant-cli/main.go:37 +0x2ba
spankenstein@Workhole supergiant-cli (master) $ go install; supergiant-cli app list
+-------+-------------------------------+-------------+
| NAME  |          CREATE TIME          | UPDATE TIME |
+-------+-------------------------------+-------------+
| test1 | 2016-04-06 19:24:56 +0000 UTC |             |
| test3 | 2016-04-06 20:58:47 +0000 UTC |             |
+-------+-------------------------------+-------------+
spankenstein@Workhole supergiant-cli (master) $ go install; supergiant-cli component create test --app test3
Success...
spankenstein@Workhole supergiant-cli (master) $ go install; supergiant-cli component list
+----------+-----------+-------------+
| APP NAME | COMP NAME | UPDATE TIME |
+----------+-----------+-------------+
| test1    | test      |             |
| test3    | test      |             |
+----------+-----------+-------------+
```

**Comment by FestivalBobcats** [comment]
I completely agree. I'll work on removing a few.

**Comment by FestivalBobcats** [comment]
I believe this issue covers the root problem here: #38
