### ISSUE TITLE
Error in RecurringService

### ISSUE THREAD

**Issue by witlox** [supergiant/supergiant#365]
When trying to do a helm release, the system crashes completely with the following stack:

time="2017-09-28T14:54:57Z" level=error msg="Error in RecurringService : Get https:///api/v1/pods?: http: no Host in request URL" 
time="2017-09-28T14:54:57Z" level=error msg="Error in RecurringService : Error creating Pod: Post https:///api/v1/namespaces/default/pods: http: no Host in request URL" 
time="2017-09-28T14:54:57Z" level=error msg="Error in RecurringService core.CapacityService: Capacity service error when fetching incoming pods: Get https:///api/v1/pods?fieldSelector=status.phase=Pending: http: no Host in request URL" 

This leaves the database in a incoherent state. When restarting the service the release is shown as green, but no pods exist. also I'm not able to delete the release.

**Comment by TheKLARKEN** [comment]
@witlox, sorry for the delay in getting back to you! I can't seem to reproduce this issue at the current time. is there any more information you might be able to provide that can help me get started on this? Thanks!

**Comment by witlox** [comment]
OK, first, I'm running on OpenStack, so I've done the following:
1. Spawn a vm, and installed supergiant according to the manual (everything OK)
2. Configure cloud connectivity (everything OK)
3. Spawn a Kube (everything OK)
4. Go to helm charts and deploy mongo on Kube (failure as specified above)

extra info:
When the kube is spawned, it creates it's own private network, but it does not attach to the public network ("master_public_ip": ""), how can I specify what network it should use?

**Comment by TheKLARKEN** [comment]
Thanks for the reply, @witlox, I'm attempting once more to reproduce this and will hopefully get back to you soon! 

As it stands with other providers on the current master, I have no issues deploying mongodb and seeing the pods, so I'm guessing this is specific to OpenStack. Have you tried doing this on the current master, yet?

**Comment by witlox** [comment]
Problem still seems to exist within master. 
pkg/model/kube.go contains the OpenStack configuration parameters, I can't find any variables for specifying what the `public` network id/name should be. Within our configuration the public network is not shared, which is likely giving the problem. When looking on the master kube, I would expect to see it attached to 2 networks (the private one that is created when spawning the kube, which is there) and the `public` network, which is not connected.

**Comment by TheKLARKEN** [comment]
That makes sense to me, it sounds like we need to adjust the OpenStack provider to appropriately fix this bug and allow Supergiant to properly speak to the cluster over the public network. I'll aim to keep you updated with any progress in this direction, as we work on it. 😁

**Comment by TheKLARKEN** [comment]
Hi, @witlox, I don't have a worthy testing environment, do you have a recommendation of an inexpensive one? Or, possible, could you help me see what can be done to properly solve this? 

Thanks again!

**Comment by witlox** [comment]
I can run the changes on our environment, I've also forked the main repo and added the changes I think might solve this issue on branch 365 (https://github.com/witlox/supergiant/tree/365).
Could you check if my changes make any sense? :)

**Comment by TheKLARKEN** [comment]
It looks fantastic! Does this work for you without any changes to the UI? Also, unrelated, I noticed that `PublicGatwayID` in the model and all functions is a misspell, probably from a long time ago. 😅

**Comment by witlox** [comment]
I'll try and test it upcoming week

**Comment by witlox** [comment]
OK, so I've been looking at the problem, and I think I've been approaching it from the wrong angle. When spawning a new node that's attached to 2 networks, there is an issue with (most) linux distributions: only one of the network interfaces is enabled by default. The first (which ever one that may be) is enabled, the other one stays down, so no IP on the public or private side. So the initial way you guys set it up (with provisioning a floating ip) is actually the way to go. I'm testing this now, using the specific internal openstack network for getting a floating ip.

**Comment by witlox** [comment]
so that works, I've got a kube running coreos which has an API that accessible under an internal openstack network (just specify the network id as the gateway id and you're good to go). maybe it's a good idea to add "install coreos image" to the tutorial :)
Next problem: 

time="2018-02-23T09:04:45Z" level=debug msg="goroutine 16 [running]:\nruntime/debug.Stack(0xc420416540, 0xc421687c30, 0x2)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x79\ngithub.com/supergiant/supergiant/pkg/core.(*RecurringService).recover(0xc42022bc80)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:55 +0x1a2\npanic(0xd90320, 0xc420010080)\n\t/usr/local/go/src/runtime/panic.go:458 +0x243\ngithub.com/supergiant/supergiant/pkg/core.newKubeScaler(0xc42022faf0, 0xc420090000, 0xc4211aa000)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/capacity_service.go:70 +0x1fb\ngithub.com/supergiant/supergiant/pkg/core.(*CapacityService).Perform(0xc42022faf0, 0xc420a01ec0, 0xc420a01ed0)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/capacity_service.go:42 +0x222\ngithub.com/supergiant/supergiant/pkg/core.(*RecurringService).perform(0xc42022bc80, 0xf50560, 0xc42022bc80)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:41 +0x5f\ngithub.com/supergiant/supergiant/pkg/core.(*RecurringService).tick(0xc42022bc80)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:32 +0x7a\ngithub.com/supergiant/supergiant/pkg/core.(*RecurringService).Run(0xc42022bc80)\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:26 +0xb8\ncreated by github.com/supergiant/supergiant/pkg/core.(*Core).InitializeBackground\n\t/ext-go/1/src/github.com/supergiant/supergiant/pkg/core/core.go:242 +0x7ec\n" 
time="2018-02-23T09:04:48Z" level=error msg="Error in RecurringService : Helm cmd failed: list\n\n" 

Helm seems to be 'down', the result from the API:

curl --insecure https://user:pass@master/api/v1/
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
    {
      "name": "bindings",
      "namespaced": true,
      "kind": "Binding"
    },
    {
      "name": "componentstatuses",
      "namespaced": false,
      "kind": "ComponentStatus"
    },
    {
      "name": "configmaps",
      "namespaced": true,
      "kind": "ConfigMap"
    },
    {
      "name": "endpoints",
      "namespaced": true,
      "kind": "Endpoints"
    },
    {
      "name": "events",
      "namespaced": true,
      "kind": "Event"
    },
    {
      "name": "limitranges",
      "namespaced": true,
      "kind": "LimitRange"
    },
    {
      "name": "namespaces",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "namespaces/finalize",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "namespaces/status",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "nodes",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "nodes/proxy",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "nodes/status",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "persistentvolumeclaims",
      "namespaced": true,
      "kind": "PersistentVolumeClaim"
    },
    {
      "name": "persistentvolumeclaims/status",
      "namespaced": true,
      "kind": "PersistentVolumeClaim"
    },
    {
      "name": "persistentvolumes",
      "namespaced": false,
      "kind": "PersistentVolume"
    },
    {
      "name": "persistentvolumes/status",
      "namespaced": false,
      "kind": "PersistentVolume"
    },
    {
      "name": "pods",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/attach",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/binding",
      "namespaced": true,
      "kind": "Binding"
    },
    {
      "name": "pods/exec",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/log",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/portforward",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/proxy",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/status",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "podtemplates",
      "namespaced": true,
      "kind": "PodTemplate"
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true,
      "kind": "ReplicationController"
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true,
      "kind": "Scale"
    },
    {
      "name": "replicationcontrollers/status",
      "namespaced": true,
      "kind": "ReplicationController"
    },
    {
      "name": "resourcequotas",
      "namespaced": true,
      "kind": "ResourceQuota"
    },
    {
      "name": "resourcequotas/status",
      "namespaced": true,
      "kind": "ResourceQuota"
    },
    {
      "name": "secrets",
      "namespaced": true,
      "kind": "Secret"
    },
    {
      "name": "serviceaccounts",
      "namespaced": true,
      "kind": "ServiceAccount"
    },
    {
      "name": "services",
      "namespaced": true,
      "kind": "Service"
    },
    {
      "name": "services/proxy",
      "namespaced": true,
      "kind": "Service"
    },
    {
      "name": "services/status",
      "namespaced": true,
      "kind": "Service"
    }
  ]
}

**Comment by TheKLARKEN** [comment]
Hey, @witlox, it's good to hear that the Openstack kube is working now! (Also, I formatted the code above a little bit, if that's ok; I just wanted to make it easier to copy/paste.)

Can you explain to me some more about when you see the Helm list error? Is there a set of things I need to do to reproduce it?
