### ISSUE TITLE
Error in RecurringService : json: cannot unmarshal string

### ISSUE THREAD

**Issue by TheKLARKEN** [supergiant/supergiant#434]
The full error is: `Error in RecurringService : json: cannot unmarshal string into Go struct field ServicePort.targetPort of type int`.

This is spat out by `supergiant/tmp/development.log`, and occurs every time I use Supergiant, regardless of specific set up or circumstance, so it should be very easy to reproduce. The specific point where this error is generated is here:
https://github.com/supergiant/supergiant/blob/fa973282f33411b6b63bbd5a96e55c281dbf2dad/pkg/core/recurring_service.go#L33

**Comment by colin-nolan** [comment]
I'm also seeing this error in the logs. On the next line, there is also:
`ERRO[0030] Recovered in RecurringService core.NodeObserver: runtime error: invalid memory address or nil pointer dereference`.

Unsure if it's related but I see this as well:
`ERRO[0091] Recovered in RecurringService core.CapacityService: runtime error: index out of range `.

Will update further if I find out more.

**Comment by colin-nolan** [comment]
Stack traces:
```
ERRO[9630] Error in RecurringService : json: cannot unmarshal string into Go struct field ServicePort.targetPort of type int 
ERRO[9630] Recovered in RecurringService core.NodeObserver: runtime error: invalid memory address or nil pointer dereference 
DEBU[9630] goroutine 244 [running]:
runtime/debug.Stack(0xc42037d740, 0xc42066d9c8, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/supergiant/supergiant/pkg/core.(*RecurringService).recover(0xc420274990)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:55 +0x199
panic(0xdbd260, 0x16dc170)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/supergiant/supergiant/pkg/core.(*NodeObserver).Perform(0xc420078fe8, 0xc420660ef8, 0xc4217d63c0)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/node_observer.go:87 +0xb21
github.com/supergiant/supergiant/pkg/core.(*RecurringService).perform(0xc420274990, 0xf529a8, 0xc420274990)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:41 +0x5f
github.com/supergiant/supergiant/pkg/core.(*RecurringService).tick(0xc420274990)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:32 +0x6d
github.com/supergiant/supergiant/pkg/core.(*RecurringService).Run(0xc420274990)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:26 +0x94
created by github.com/supergiant/supergiant/pkg/core.(*Core).InitializeBackground
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/core.go:255 +0x103
 
ERRO[9660] Recovered in RecurringService core.CapacityService: runtime error: index out of range 
DEBU[9660] goroutine 243 [running]:
runtime/debug.Stack(0xc42037d740, 0xc421fbfc70, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/supergiant/supergiant/pkg/core.(*RecurringService).recover(0xc420274960)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:55 +0x199
panic(0xdbd260, 0x16dc1b0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/supergiant/supergiant/pkg/core.newKubeScaler(0xc420284040, 0xc4203c2000, 0xc420aa8300)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/capacity_service.go:72 +0x368
github.com/supergiant/supergiant/pkg/core.(*CapacityService).Perform(0xc420284040, 0xc420663ef8, 0xc4217d6bc0)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/capacity_service.go:44 +0x1c0
github.com/supergiant/supergiant/pkg/core.(*RecurringService).perform(0xc420274960, 0xf529a8, 0xc420274960)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:41 +0x5f
github.com/supergiant/supergiant/pkg/core.(*RecurringService).tick(0xc420274960)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:32 +0x6d
github.com/supergiant/supergiant/pkg/core.(*RecurringService).Run(0xc420274960)
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:26 +0x94
created by github.com/supergiant/supergiant/pkg/core.(*Core).InitializeBackground
	/root/supergiant/src/github.com/supergiant/supergiant/pkg/core/core.go:247 +0x6a2
```
