### ISSUE TITLE
1.0: Recovered in RecurringService core.NodeObserver on DO clusters

### ISSUE THREAD

**Issue by TheKLARKEN** [supergiant/supergiant#435]
The full trace and error message:
```
ERRO[76111] Recovered in RecurringService core.NodeObserver: runtime error: invalid memory address or nil pointer dereference
DEBU[76111] goroutine 263 [running]:
runtime/debug.Stack(0xc42037e800, 0xc421815918, 0x2)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/supergiant/supergiant/pkg/core.(*RecurringService).recover(0xc4205ee060)
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:55 +0x199
panic(0x4a64620, 0x51adce0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/supergiant/supergiant/pkg/core.(*NodeObserver).Perform(0xc420286fb0, 0xc421a3fee8, 0xc4211bdf40)
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/node_observer.go:87 +0xb13
github.com/supergiant/supergiant/pkg/core.(*RecurringService).perform(0xc4205ee060, 0x4bf86f8, 0xc4205ee060)
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:41 +0x5f
github.com/supergiant/supergiant/pkg/core.(*RecurringService).tick(0xc4205ee060)
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:32 +0x6d
github.com/supergiant/supergiant/pkg/core.(*RecurringService).Run(0xc4205ee060)
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/recurring_service.go:26 +0xb8
created by github.com/supergiant/supergiant/pkg/core.(*Core).InitializeBackground
	/Users/clarkevennerbeck/go/src/github.com/supergiant/supergiant/pkg/core/core.go:255 +0x103
```

This is the full background of the error:
* After creating a DO cluster, the CPU metrics don't populate the metrics fields on the specific cluster's page (figure 1).
* However, the metrics on the main clusters page do populate (figure 2).
* The error begins after a few minutes on its own, reoccurring every time the recurring service ticks, and it doesn't stop until deletion of the cluster.

Also, I've only observed this on DO clusters.

### Figure 1:
![supergiant 2](https://user-images.githubusercontent.com/23109047/36433750-e8199af0-1622-11e8-815a-69a3efb50b8e.png)

### Figure 2:
![supergiant 3](https://user-images.githubusercontent.com/23109047/36433834-215c2eb8-1623-11e8-87c0-3ca25e700e48.png)

**Comment by gopherstein** [comment]
Closing due to age.
