### ISSUE TITLE
1.0.0-beta3 Can't use sqlite on either linux or in docker

### ISSUE THREAD

**Issue by mclark4386** [supergiant/supergiant#468]
If you try to use docker with the following:
`docker run -it supergiant/supergiant-api /supergiant-api --publish-host localhost --http-port 80 --sqlite-file supergiant.db`
You will get this error:
```
panic: sql: unknown driver "sqlite3" (forgotten import?) [recovered]
	panic: sql: unknown driver "sqlite3" (forgotten import?)

goroutine 1 [running]:
panic(0xcd6d20, 0xc420011d50)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.HandleAction.func1(0xc420277858)
	/home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:478 +0x247
panic(0xcd6d20, 0xc420011d50)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/supergiant/supergiant/pkg/core.(*Core).Initialize(0xc4202b7e00)
	/home/travis/gopath/src/github.com/supergiant/supergiant/pkg/core/core.go:105 +0x10a
main.main.func1(0xc4202d23c0)
	/home/travis/gopath/src/github.com/supergiant/supergiant/cmd/server/server.go:34 +0x49
reflect.Value.call(0xc71740, 0xc4200119d0, 0x13, 0xe476b4, 0x4, 0xc420277818, 0x1, 0x1, 0x4d6fa8, 0xe31120, ...)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc71740, 0xc4200119d0, 0x13, 0xc420277818, 0x1, 0x1, 0x1, 0x2, 0x2)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:302 +0xa4
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.HandleAction(0xc71740, 0xc4200119d0, 0xc4202d23c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:487 +0x1e0
github.com/supergiant/supergiant/vendor/github.com/urfave/cli.(*App).Run(0xc4203c8000, 0xc42000a0e0, 0x7, 0x7, 0x0, 0x0)
	/home/travis/gopath/src/github.com/supergiant/supergiant/vendor/github.com/urfave/cli/app.go:245 +0x59b
main.main()
	/home/travis/gopath/src/github.com/supergiant/supergiant/cmd/server/server.go:176 +0xc58
```

The exact same thing happens if try it on an ubuntu 16.04 box (with or without sqlite installed).

**Comment by gopherstein** [comment]
@golkir  I think we should prob put out an install doc soon. I am going to get something together to get @mclark4386 by but we should move that high on our priority.

**Comment by catroot** [comment]
The same issue with 1.0.0-beta4:

'''
./supergiant-api-linux-amd64 --config-file ~/supergiant/config.json
panic: sql: unknown driver "sqlite3" (forgotten import?) [recovered]
        panic: sql: unknown driver "sqlite3" (forgotten import?)
'''

**Comment by timdp** [comment]
I'm running into this when following [the DigitalOcean tutorial](https://supergiant.io/blog/how-to-run-supergiant-server-digitalocean) with v1.1.0. Does this mean the issue is still not resolved? Or should I install a dependency?

**Comment by TheKLARKEN** [comment]
@timdp Yes, this issue is still unresolved, but I'm trying to get the team focused on it. As soon as things are properly set up, we're going to update these tutorials and docs to properly equip users. 🙂 Thanks for letting us know which tutorial you were looking at, we appreciate the extra voice on this!

**Comment by TheKLARKEN** [comment]
The docs have been updated! https://supergiant.readme.io/v1.1.0/docs/linux 

Hopefully this satisfies this particular issue. 🙂 Regarding the tutorials, those are unrelated to this issue, but we're going to get started on fixing those. I'll leave this open for a few more business days and then close it if all seems well. 🙂
